config/routes.rb
Rails.application.routes.draw do


  mount ActionCable.server => '/cable'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {
    sessions: 'sessions',
    passwords: 'passwords',
    confirmations: 'confirmations',
    :registrations => 'registrations'
  }
  get "home/index" 
  root to: 'home#index'
  
  get "home/find_jobs" => "home#find_jobs"

  resources :messages


  namespace :recruiters do
    resources :dashboard do
      collection do
          get  :my_account
          post  :my_account
          get  :user_list
          get  :chat_with_candidate
      end
    end 
    resources :jobs  do
      collection do
          get  :candidates
          get  :download_pdf
          get  :view_application
      end
      member do
        get  :approve_resume
        get  :reject_resume
      end
    end
  end


  namespace :applicants do
    resources :dashboard do
      member do
        get :application_detail
        # get :subscription
        match  :subscription, via: [:get,  :post]
      end
      collection do
        match  :job, via: [:get,  :post]
        get :my_applications
      end
    end 

    resources :jobs, only: [:show, :index] do
      member do
        post  :apply_job
        get  :add_to_favorites
        get :job_detail
        put :favorite
      end
      collection do
        get :all_jobs
        get  :my_favourite_jobs
      end
    end 
    
    # resources :recipes do
    # end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/applicants/dashboard_controller.rb
class Applicants::DashboardController < ApplicationController
	
	include Applicants

	def new
		
	end

	def index
		get_all_jobs
		@part_time_jobs = @jobs.part_time   
		@full_time_jobs =@jobs.full_time
	end

	def my_account
				current_user.update(user_params) if request.post?
	end

	def my_applications
		@my_jobs = current_user.applied_jobs
	end


	def application_detail
		@applied_job = AppliedJob.find_by_job_id(params[:id])
	end

	def subscription
		if request.post?
		check_stripe_customer_id  unless current_user.stripe_customer_id  			
		Stripe.api_key = STRIPE_SECRET
		# Create a  payment
		begin
			payment = Stripe::PaymentMethod.create({
								  type: 'card',
									card: {
									number: params[:card_number],
									exp_month: params[:exp_month],
									exp_year: params[:exp_year],
									cvc: params[:cvc]
									}
								})

			puts "============payment created=========================="

		Stripe::PaymentMethod.attach(
									  payment.id,
									  {customer: current_user.stripe_customer_id},
									)
		puts "============pay method attached=========================="
		# update customer default payment method
			pay_method  = Stripe::Customer.update(
												current_user.stripe_customer_id, 
												{invoice_settings: 
													{default_payment_method: payment.id}
												},
											)
		puts "============ pay method updated=========================="
		# Create subscription
			plan = Plan.first
			subscribe  =	Stripe::Subscription.create({
											  customer: current_user.stripe_customer_id,
											  items: [
											    {price: plan.stripe_price_id},
											  ]
											})
			puts "============subscription created=========================="
			subscription = current_user.build_subscription(subscription_params) if subscribe
		rescue StandardError => e
			puts "============#{e.message}=========================="
		end
			
		# if request.post?
			# success = false
			# Stripe.api_key = STRIPE_SECRET
			# 	begin
			# 		card = Stripe::Token.create({
			# 			card: {
			# 			number: params[:card_number],
			# 			exp_month: params[:exp_month],
			# 			exp_year: params[:exp_year],
			# 			cvc: params[:cvc]
			# 			},
			# 		})

			# 	  charge = Stripe::Charge.create({
			# 		  amount: params[:paid_amount].to_i*100,  
			# 		  currency: "INR",
			# 		  source: card.id,
			# 		})

			# 		subscription = current_user.build_subscription(subscription_params) if charge&.paid
			# 		subscription.save!
					# render json: {success: true, message:'Subscription done.'}

				# rescue StandardError => e
				#   flash[:error] = e.message
				# end
				

		end

	end
	
end
private
	def subscription_params
		params.permit(:user_id, :paid_amount,:start_date,:end_date)
	end

app/controllers/concerns/recruiter.rb
module Recruiters
  include ActiveSupport::Concern

    included do
      before_action :my_uploaded_jobs, only: [:index]
    end

  def my_uploaded_jobs
    @jobs = current_user.jobs

  end

end

app/controllers/recruiters/dashboard_controller.rb
class Recruiters::DashboardController < ApplicationController

	def new
		
	end

	def index
		
	end

	def my_account
		current_user.update(user_params) if request.post?
	end
	
	def user_list
        @users = User.all 
    end 

    def chat_with_candidate
        @sender = User.find(params[:user_id])
        @receiver = User.find(params[:receiver_id])
        @messages = Message.where(sender_id: @sender.id, receiver_id: @receiver.id).or(Message.where(sender_id: @receiver.id, receiver_id: @sender.id))
        @chat_id = [@sender.id, @receiver.id].sort.join("") #generates a unique identifier for a pair of user 
    end 
end

private
def user_params
	params.require(:user).permit(:name,:dp, :qualification, :address,  :phone, :total_experience )
	
end

app/controllers/recruiters/jobs_controller.rb
class Recruiters::JobsController < ApplicationController
	load_and_authorize_resource
	include  Recruiters
	def new
		@job = Job.new
	end

	def index
		@jobs = @jobs.paginate(page: params[:page], per_page: 5)
	end

	def candidates
		@jobs =  AppliedJob.includes(:job).where(recruiter_id: current_user.id).paginate(page: params[:page], per_page: 5)
	end

	def edit
		@job = Job.find_by_id(params[:id])
	end
	
	def create
		job = Job.new(job_params)
		job.save!
		EmailWorker.perform_async  'posted_job', job.id
		redirect_to recruiters_jobs_path, notice: "Job added."
	end

	def update
		job = Job.find_by_id(params[:id])
		job.update(job_params)
		EmailWorker.perform_async  'posted_job', job.id
		redirect_to recruiters_jobs_path, notice: "Job updated."
		
	end

	def approve_resume
		byebug
		job = AppliedJob.find_by_id(params[:id])
		job.update(status: 'approved')
	end


	def reject_resume
		byebug
		job = AppliedJob.find_by_id(params[:id])
		job.update(status: 'rejected')
	end

	def destroy
		job = Job.find_by_id(params[:id])
		job.destroy
		redirect_to recruiters_jobs_path, notice: "Job deleted."
		
	end

end

private

def job_params
	params.require(:job).permit(:company_name, :title, :skills, :job_type, :description, :locality, :user_id, :category, :type, :closing_date)
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/views/recruiters/dashboard/chat_with_candidate.html.erb
<div style="margin-top: 10%;">
    <h2><%=@sender.name %> contacting <%=@receiver.name%></h2>
    <div id="messages">
        <% @messages.each do |message| %>
            <p><%= message.sender.name %>: <%= message.text %></p>
        <% end %>
    </div>
    
    <%= form_tag messages_path  do %>
        <div>
            <%= text_field_tag :message, nil ,  placeholder: 'Type message here...', class: 'form-control' %>
            <%= hidden_field_tag "receiver_id", @receiver.id %>
            <%= hidden_field_tag "sender_id", @sender.id %>
            <%= hidden_field_tag "chat_id", @chat_id %>
            <%= submit_tag "Send", data: { disable_with: false } %>
        </div>
    <% end %>
</div>

app/views/recruiters/dashboard/index.html.erb
After login page for recruiters
<div>
		<%= link_to 'Add a job', new_recruiters_job_path %>
</div>
	
<div>
		<%= link_to 'List job', recruiters_jobs_path %>
</div>
	
<div>
		<%= link_to 'Recived application ', candidates_recruiters_jobs_path %>
</div>
	

<%= link_to 'Sign out', destroy_user_session_path ,:method => :delete %>

app/views/recruiters/dashboard/my_account.html.erb
<main>
  <!-- Featured_job_start -->
  <section class="featured-job-area feature-padding">
    <div class="container">
      <!-- Section Tittle -->
      <div class="row">
        <div class="col-lg-12">
          <div class="section-tittle text-center">
            <span>Recent Job</span>
            <h2>Featured Jobs</h2>
          </div>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-xl-10">
          <!-- single-job-content -->
          <div class="single-job-items mb-30">
            <div class="job-items">
              <div class="company-img">
                <a href="job_details.html"><img src="assets/img/icon/job-list1.png" alt=""></a>
              </div>
              <div class="job-tittle">
                <a href="job_details.html">
                  <h4>Digital Marketer</h4>
                </a>
                <ul>
                  <li>Creative Agency</li>
                  <li><i class="fas fa-map-marker-alt"></i>Athens, Greece</li>
                  <li>$3500 - $4000</li>
                </ul>
              </div>
            </div>
            <div class="items-link f-right">
              <a href="job_details.html">Full Time</a>
              <span>7 hours ago</span>
            </div>
          </div>
          <!-- single-job-content -->
          <div class="single-job-items mb-30">
            <div class="job-items">
              <div class="company-img">
                <a href="job_details.html"><img src="assets/img/icon/job-list2.png" alt=""></a>
              </div>
              <div class="job-tittle">
                <a href="job_details.html">
                  <h4>Digital Marketer</h4>
                </a>
                <ul>
                  <li>Creative Agency</li>
                  <li><i class="fas fa-map-marker-alt"></i>Athens, Greece</li>
                  <li>$3500 - $4000</li>
                </ul>
              </div>
            </div>
            <div class="items-link f-right">
              <a href="job_details.html">Full Time</a>
              <span>7 hours ago</span>
            </div>
          </div>
          <!-- single-job-content -->
          <div class="single-job-items mb-30">
            <div class="job-items">
              <div class="company-img">
                <a href="job_details.html"><img src="assets/img/icon/job-list3.png" alt=""></a>
              </div>
              <div class="job-tittle">
                <a href="job_details.html">
                  <h4>Digital Marketer</h4>
                </a>
                <ul>
                  <li>Creative Agency</li>
                  <li><i class="fas fa-map-marker-alt"></i>Athens, Greece</li>
                  <li>$3500 - $4000</li>
                </ul>
              </div>
            </div>
            <div class="items-link f-right">
              <a href="job_details.html">Full Time</a>
              <span>7 hours ago</span>
            </div>
          </div>
          <!-- single-job-content -->
          <div class="single-job-items mb-30">
            <div class="job-items">
              <div class="company-img">
                <a href="job_details.html"><img src="assets/img/icon/job-list4.png" alt=""></a>
              </div>
              <div class="job-tittle">
                <a href="job_details.html">
                  <h4>Digital Marketer</h4>
                </a>
                <ul>
                  <li>Creative Agency</li>
                  <li><i class="fas fa-map-marker-alt"></i>Athens, Greece</li>
                  <li>$3500 - $4000</li>
                </ul>
              </div>
            </div>
            <div class="items-link f-right">
              <a href="job_details.html">Full Time</a>
              <span>7 hours ago</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

app/views/recruiters/dashboard/oldmy_account.html.erb
<style type="text/css">
	.avatar-wrapper {
	 position: relative;
	 height: 200px;
	 width: 200px;
	 margin: 50px auto;
	 border-radius: 50%;
	 overflow: hidden;
	 box-shadow: 1px 1px 15px -5px black;
	 transition: all 0.3s ease;
}
 .avatar-wrapper:hover {
	 transform: scale(1.05);
	 cursor: pointer;
}
 .avatar-wrapper:hover .profile-pic {
	 opacity: 0.5;
}
 .avatar-wrapper .profile-pic {
	 height: 100%;
	 width: 100%;
	 transition: all 0.3s ease;
}
 .avatar-wrapper .profile-pic:after {
	 font-family: FontAwesome;
	 content: "\f007";
	 top: 0;
	 left: 0;
	 width: 100%;
	 height: 100%;
	 position: absolute;
	 font-size: 190px;
	 background: #ecf0f1;
	 color: #34495e;
	 text-align: center;
}
 .avatar-wrapper .upload-button {
	 position: absolute;
	 top: 0;
	 left: 0;
	 height: 100%;
	 width: 100%;
}
 .avatar-wrapper .upload-button .fa-arrow-circle-up {
	 position: absolute;
	 font-size: 234px;
	 top: -17px;
	 left: 0;
	 text-align: center;
	 opacity: 0;
	 transition: all 0.3s ease;
	 color: #34495e;
}
 .avatar-wrapper .upload-button:hover .fa-arrow-circle-up {
	 opacity: 0.9;
}
 
</style>

<div class="container" style="margin-top:10%">
	<div class="row" id="main">
<div class="col-md-12">
    	<%#= form_for(resource, as: resource_name, url: user_registration_path) do |f| %>
    	<%= form_for current_user, url: my_account_recruiters_dashboard_index_path , method: :post, :html =>   {:role => "form"} do |f| %>
			<h2>Edit your profile.<small>It's always easy</small></h2>
			<hr class="colorgraph">
			<div class="avatar-wrapper">
				<img class="profile-pic" src="" />
				<div class="upload-button">
					<%if current_user.dp.exists?%>
              				<%=  image_tag(current_user.dp.url(:thumb), :class => "common-img",  style: "height:169;width:169", alt: "Profile Image") %>
            		<%else%>
						<i class="fa fa-arrow-circle-up" aria-hidden="true"></i>
            		<%end%>
				</div>
				<!-- <input class="file-upload" type="file"  name="user[dp]" accept="image/*"/> -->
				<%= f.file_field :dp, class:"file-upload" %> 
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
						<!-- <input type="password" name="password" id="password" class="form-control input-lg" placeholder="Password" tabindex="5"> -->
						<%= f.text_field :name, autofocus: true, autocomplete: "name",placeholder: "Name", class:"form-control input-lg" %>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
						<%= f.email_field :email, readonly: true, autocomplete: "email", placeholder:'Email', class:'form-control input-lg' %>
						<!-- <input type="password" name="password_confirmation" id="password_confirmation" class="form-control input-lg" placeholder="Confirm Password" tabindex="6"> -->

					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
						<%= f.text_field :phone, autofocus: true, autocomplete: "phone",placeholder: "Contact Number", class:"form-control input-lg" %>
						<!-- <input type="password" name="password" id="password" class="form-control input-lg" placeholder="Password" tabindex="5"> -->
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
						<%= f.text_field :address, autofocus: true, autocomplete: "address",placeholder: "Address", class:"form-control input-lg" %>
						<!-- <input type="password" name="password_confirmation" id="password_confirmation" class="form-control input-lg" placeholder="Confirm Password" tabindex="6"> -->
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
						<%= f.text_field :total_experience, autofocus: true, autocomplete: "total_experience",placeholder: "Total Experience", class:"form-control input-lg" %>
						<!-- <input type="password" name="password" id="password" class="form-control input-lg" placeholder="Password" tabindex="5"> -->
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
						<%= f.text_field :qualification, autofocus: true, autocomplete: "qualification",placeholder: "Qualifications", class:"form-control input-lg" %>
						<!-- <input type="password" name="password_confirmation" id="password_confirmation" class="form-control input-lg" placeholder="Confirm Password" tabindex="6"> -->
					</div>
				</div>
			</div>
			<hr class="colorgraph">
			<div class="row">
				<div class="col-xs-12 col-md-6"></div>
				<div class="col-xs-12 col-md-6">
					<!-- <a href="#" class="btn btn-success btn-block btn-lg">Save</a> -->
					<%=  f.button  "Save", class:"btn btn-success btn-block btn-lg" %>
				</div>
			</div>
		<% end %>
	</div>
	</div>
	</div>
	<script type="text/javascript">
	$(document).ready(function() {
	
    var readURL = function(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('.profile-pic').attr('src', e.target.result);
            }
    
            reader.readAsDataURL(input.files[0]);
        }
    }
   
    $(".file-upload").on('change', function(){
        readURL(this);
    });
    
    $(".upload-button").on('click', function() {
       $(".file-upload").click();
    });
});</script>

app/views/recruiters/dashboard/user_list.html.erb
<div>
    <h1>Contacts</h1>
    <div style="margin-top:10%">
        <%= form_for :users, :url => chat_with_candidate_recruiters_dashboard_index_path,  :html => { :method => 'GET' } do |f| %>
            <%= hidden_field_tag "user_id", current_user.id%>
            <%= hidden_field_tag "receiver_id", 2%>
            
            <%= f.submit "Chat"%>
        <% end %>
    </div>
</div>