config/routes.rb
Rails.application.routes.draw do


  mount ActionCable.server => '/cable'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {
    sessions: 'sessions',
    passwords: 'passwords',
    confirmations: 'confirmations',
    :registrations => 'registrations'
  }
  get "home/index" 
  root to: 'home#index'
  
  get "home/find_jobs" => "home#find_jobs"

  resources :messages


  namespace :recruiters do
    resources :dashboard do
      collection do
          get  :my_account
          post  :my_account
          get  :user_list
          get  :chat_with_candidate
      end
    end 
    resources :jobs  do
      collection do
          get  :candidates
          get  :download_pdf
          get  :view_application
      end
      member do
        get  :approve_resume
        get  :reject_resume
      end
    end
  end


  namespace :applicants do
    resources :dashboard do
      member do
        get :application_detail
        # get :subscription
        match  :subscription, via: [:get,  :post]
      end
      collection do
        match  :job, via: [:get,  :post]
        get :my_applications
      end
    end 

    resources :jobs, only: [:show, :index] do
      member do
        post  :apply_job
        get  :add_to_favorites
        get :job_detail
        put :favorite
      end
      collection do
        get :all_jobs
        get  :my_favourite_jobs
      end
    end 
    
    # resources :recipes do
    # end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :recruiter
      can :new, Job
      can :create, Job
      can :index, Job
      can :edit, Job
      can :update, Job
      can :candidates, Job
      can :download_pdf, Job
      can :destroy, Job
      can :user_list, Job
      can :chat_with_candidate, Job
      can :candidates, Job
      can :view_application, Job
    elsif user.has_role? :applicant
      can :show, Job
      can :index, Job
      can :all_jobs, Job
      can :job_detail, Job
      can :apply_job, Job
      can :my_favourite_jobs, Job
      can :favorite, Job
      can :user_list, Job
      can :application_detail, Job
      can :chat_with_candidate, Job
    end  
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/applied_job.rb
class AppliedJob < ApplicationRecord
	has_attached_file :resume
   validates_attachment_content_type :resume,
   :content_type => ["application/pdf"]




	# belongs_to :user, optional: true
	belongs_to :job, optional: true
	has_many :applicants, :class_name => 'User', :foreign_key => :applicant_id

	belongs_to :applicant, :class_name => "User"
	belongs_to :recruiter, :class_name => "User"
end

app/models/favorite_job.rb
class FavoriteJob < ApplicationRecord
	 belongs_to :job
  belongs_to :user
end

app/models/job.rb
class Job < ApplicationRecord
 
	belongs_to :user, optional: true
  	has_many :applied_jobs, :class_name => 'AppliedJob', :foreign_key => :job_id
  	has_many :favorite_jobs
  	has_many :favorited_by, through: :favorite_jobs, source: :user 
  	enum job_type: [ :part_time, :full_time]
	scope :part_time, -> { where(job_type: 'part_time') }
	scope :full_time, -> { where(job_type: 'full_time') }
	scope :featured_jobs, -> {where("created_at >= ? AND created_at <= ?", Date.today -  2.months, Date.today )}

end

app/models/message.rb
class Message < ApplicationRecord
	   belongs_to :sender, class_name: 'User'
    belongs_to :receiver, class_name: 'User'
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  attr_accessor :role
  after_create  :create_stripe_customer
  # enum role: [ :applicant, :recruiter]
  rolify
  has_many :jobs
  has_many :applied_jobs, :class_name => 'AppliedJob', :foreign_key => :applicant_id
  has_one :subscription


  has_many :favorite_jobs  
  
  has_many :favorites, through: :favorite_jobs, source: :job # the actual recipes a user favorites


   has_many :messagee, foreign_key: :receiver_id, class_name: 'Message'  
    has_many :senders, through: :messagee
    has_many :messaged, foreign_key: :sender_id, class_name: 'Message'
    has_many :receivers, through: :messaged

      has_attached_file :dp
    validates_attachment :dp,
                     content_type: { content_type: /\Aimage\/.*\z/ }



  def create_stripe_customer
    user  = User.last
    Stripe.api_key = STRIPE_SECRET
    cutomer = Stripe::Customer.create({
          email: user.email,
        })  
    user.update(stripe_customer_id: cutomer.id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
 
    def create 
        message = Message.create(sender_id: params[:sender_id], receiver_id: params[:receiver_id], text: params[:message])
        SendMessageJob.perform_later(message)

    end 
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/unlocks_controller.rb
# frozen_string_literal: true

class UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
	def recruiter_id(job_id)
		Job.find_by_id(job_id).user_id

	end

	def already_applied(job)
		job.applied_jobs.find_by(applicant_id:current_user.id)
	end

	def is_favorite(job)
		job.favorited_by.map(&:id).include? current_user.id
	end

	def applied_date(job)
		if job.applied_date.present?
			job.applied_date.try(:strftime, "%D")
		else
			''
		end
	end
 def current_class?(path)
    current_route = Rails.application.routes.recognize_path(path)
    return 'active' if current_page?(path) or params[:controller] == current_route[:controller]

    # return 'active' if request.path == path
    ''
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
  :user
end

def resource
  @resource ||= User.new
end

def devise_mapping
  @devise_mapping ||= Devise.mappings[:user]
end

def resource_class
  devise_mapping.to
end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>JobBoard</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="manifest" href="site.webmanifest">
  <link rel="shortcut icon" type="image/x-icon" href="/assets/images/favicon.ico">
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
	<body>
		    <!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <!-- <img src="assets/img/logo/logo.png" alt=""> -->
                    <%=image_pack_tag('media/img/company.png')%>
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->

	  <!-- <div class="main-wrapper"> -->
	    <!-- header start -->
	    <%= render "layouts/frontend/header" %>
	    <!-- header end -->
	    <%#= render "layouts/elements/frontend/flash" %>
	    <!-- <div class="vh-100 d-flex justify-content-center align-items-center"> -->
			  <!-- <h2>Main Content</h2> -->
	      <%= render 'layouts/shared/message' %>

          <%= yield %>
			<!-- </div> -->
	  <!-- </div> -->
	  
	  	<!-- <p class="text-center p-4 m-0">Footer Content</p> -->
	    <%= render "layouts/frontend/footer" %>
		
	    <!-- footer end -->
	</body>
	    <%#= javascript_pack_tag 'jquery-min.js' %>

</html>

app/views/layouts/frontend/_footer.html.erb
  <footer>
        <!-- Footer Start-->
        <div class="footer-area footer-bg footer-padding">
            <div class="container">
                <div class="row d-flex justify-content-between">
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                       <div class="single-footer-caption mb-50">
                         <div class="single-footer-caption mb-30">
                             <div class="footer-tittle">
                                 <h4>About Us</h4>
                                 <div class="footer-pera">
                                     <p>Heaven frucvitful doesn't cover lesser dvsays appear creeping seasons so behold.</p>
                                </div>
                             </div>
                         </div>

                       </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Contact Info</h4>
                                <ul>
                                    <li>
                                    <p>Address :Your address goes
                                        here, your demo address.</p>
                                    </li>
                                    <li><a href="#">Phone : +91 7000474153</a></li>
                                    <li><a href="#">Email : info@jobboard.com</a></li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Important Link</h4>
                                <ul>
                                    <li><a href="#"> View Project</a></li>
                                    <li><a href="#">Contact Us</a></li>
                                    <li><a href="#">Testimonial</a></li>
                                    <li><a href="#">Proparties</a></li>
                                    <li><a href="#">Support</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Newsletter</h4>
                                <div class="footer-pera footer-pera2">
                                 <p>Heaven fruitful doesn't over lesser in days. Appear creeping.</p>
                             </div>
                             <!-- Form -->
                             <div class="footer-form" >
                                 <div id="mc_embed_signup">
                                     <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                     method="get" class="subscribe_form relative mail_part">
                                         <input type="email" name="email" id="newsletter-form-email" placeholder="Email Address"
                                         class="placeholder hide-on-focus" onfocus="this.placeholder = ''"
                                         onblur="this.placeholder = ' Email Address '">
                                         <div class="form-icon">
                                             <button type="submit" name="submit" id="newsletter-submit"
                                             class="email_icon newsletter-submit button-contactForm">
                                             <%=image_pack_tag('media/img/icon/form.png')%>
                                         </div>
                                         <div class="mt-10 info"></div>
                                     </form>
                                 </div>
                             </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- footer-bottom area -->
        <div class="footer-bottom-area footer-bg">
            <div class="container">
                <div class="footer-border">
                     <div class="row d-flex justify-content-between align-items-center">
                         <div class="col-xl-10 col-lg-10 ">
                             <div class="footer-copy-right">
                                 <p>
  Copyright &copy;<script>document.write(new Date().getFullYear());</script><i class="fa fa-heart" aria-hidden="true"></i> by <a href="#" target="_blank">PK</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                             </div>
                         </div>
                     </div>
                </div>
            </div>
        </div>
        <!-- Footer End-->
    </footer>

app/views/layouts/frontend/_header.html.erb
    <header>
        <!-- Header Start -->
       <div class="header-area header-transparrent">
           <div class="headder-top header-sticky">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-3 col-md-2">
                            <!-- Logo -->
                            <div class="logo">
                                <!-- <a href="index.html"><img src="assets/img/logo/logo.png" alt=""></a> -->
                                <%=link_to( image_pack_tag('media/img/company.png', :class => 'company_img', alt: "company-image", :width => "140", :height => "90"),  root_path) %>
                            </div>  
                        </div>
                        <%if current_user.present?%>
                        <div class="col-lg-9 col-md-9">
                            <div class="menu-wrapper">
                                <!-- Main-menu -->
                                <div class="main-menu">
                                    <nav class="d-none d-lg-block">
                                      <ul id="navigation">
                                        <%if current_user.has_role? :recruiter%>
                                          <li><a href="<%=new_recruiters_job_path%>">Post Job</a></li>
                                          <li><a href="<%=candidates_recruiters_jobs_path%>">Candidates </a></li>
                                          <li><a href="<%=recruiters_jobs_url%>">Jobs</a></li>
                                          <li><a href="#">Page</a>
                                              <ul class="submenu">
                                                  <li><a href="blog.html">Blog</a></li>
                                                  <li><a href="single-blog.html">Blog Details</a></li>
                                                  <li><a href="elements.html">Elements</a></li>
                                                  <li><a href="job_details.html">job Details</a></li>
                                              </ul>
                                          </li>
                                      <%elsif current_user.has_role? :applicant%>
                                        <li><a href="<%=my_applications_applicants_dashboard_index_path%>">My Applications</a></li>
                                        <li><a href="<%=applicants_jobs_url%>">Jobs</a></li>
                                        <%unless current_user.subscription %>
                                        <li><a href="<%=subscription_applicants_dashboard_url(current_user.id)%>">Upgrade 
                                        to Premium</a></li>
                                        <%end%>
                                        <li><a href="#">Page</a>
                                            <ul class="submenu">
                                                <li><a href="blog.html">Blog</a></li>
                                                <li><a href="single-blog.html">Blog Details</a></li>
                                                <li><a href="elements.html">Elements</a></li>
                                                <li><a href="job_details.html">job Details</a></li>
                                            </ul>
                                        </li>
                                        <%end%>
                                      </ul>
                                    </nav>
                                </div>          
                                <!-- Header-btn -->
                                <div class="header-btn d-none f-right d-lg-block">
                                    <%= link_to 'Upgrade', subscription_applicants_dashboard_url(current_user.id), method: :get, class: "btn head-btn2" %>
                                    <%= link_to 'Sign out', destroy_user_session_path, method: :get, class: "btn head-btn2" %>
                                </div>
                            </div>
                        </div>
                        <%else%>
                        <div class="col-lg-9 col-md-9">
                            <div class="menu-wrapper">
                                <!-- Main-menu -->
                                <div class="main-menu">
                                    <nav class="d-none d-lg-block">
                                        <ul id="navigation">
                                            <li><a href="<%=root_path%>">Home</a></li>
                                            <li><a href="<%=home_find_jobs_path%>">Find a Jobs </a></li>
                                            <li><a href="about.html">About</a></li>
                                            <li><a href="#">Page</a>
                                                <ul class="submenu">
                                                    <li><a href="blog.html">Blog</a></li>
                                                    <li><a href="single-blog.html">Blog Details</a></li>
                                                    <li><a href="elements.html">Elements</a></li>
                                                    <li><a href="job_details.html">job Details</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="contact.html">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>          
                                <!-- Header-btn -->
                                <div class="header-btn d-none f-right d-lg-block">
                                 

                                    <a href="#" data-toggle="modal" data-target="#register" class="btn head-btn1">Register</a>
                                    <a href="#" data-toggle="modal" data-target="#productModal" class="btn head-btn2">Login</a>
                                </div>
                            </div>
                        </div>
                        <%end%>


                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
           </div>
       </div>
        <!-- Header End -->
    </header>
    <%unless current_user.present?%>
      <%=   render partial: 'layouts/frontend/registeration_form'%>
      <%=   render partial: 'layouts/frontend/login_form'%>
    <%end%>

app/views/layouts/frontend/_login_form.html.erb
<div class="modal fade " id="productModal" tabindex="-1" aria-labelledby="productModal" aria-hidden="true">
   <div class="modal-dialog custom-modal modal-lg" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h2 class="modal-title title-sm mb-0 modal-title" id="exampleModalLabel">Login</h2>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <div class="calendar-outer">
               <%= form_for(resource, as: resource_name, url: new_user_session_path,  :html => {:id => "login_form"} ) do |f| %>
               <%#= form_for(resource, as: resource_name, url: new_user_session_path), :method => 'post', :class=>'form-contact contact_form', id:"payment-form", novalidate:'novalidate' do %>
                  <div class="row">
                     <div class=" col-12">
                        <div class="form-group">
                           <label for="cc-number-label" class="control-label">Email*</label>
                           <!-- <input id="cc-number" type="tel" value="4242424242424242"  class="input-lg form-control cc-number" autocomplete="cc-number" placeholder="•••• •••• •••• ••••" name="card_number"> -->
                           <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder:'Email', class:'input-lg form-control' %>
                        </div>
                     </div>
                     <div class="col-12">
                        <div class="form-group">
                           <label for="cc-exp-label" class="control-label">Password*</label>
                            <%= f.password_field :password, autocomplete: "current-password", class:"input-lg form-control ",   placeholder:'Password' %>
                           <!-- <input id="cc-exp" type="tel" value="12 / 2024" class="input-lg form-control cc-exp" autocomplete="cc-exp" placeholder="•• / ••••" name="card_expiry_date"> -->
                        </div>
                     </div>
                  </div>
                  <button type="submit" class="btn cl-btn grd-bg text-uppercase mr-md-4 mr-sm-3 mr-2" title="Login">Login</button>
               <%end%>
            </div>
         </div>
      </div>
   </div>
</div>        

<script type="text/javascript">
      $("#login_form").validate({
        rules: {
          "user[name]": {
            required: true,
            minlength: 4,
            maxlength: 50,
          },
          "user[email]": {
            required: true,
            isValidEmailAddress:true
          },
          "user[password]": {
            required: true,
            minlength: 6,
            maxlength: 20,
          },
          "user[confirm_password]": {
            required: true,
            minlength: 6,
            equalTo: "#user_password",
          }
        },
        messages: {
          "user[user_name]": {
              required: "Please enter username."
          },
          "user[email]": {
              required: "Please enter email.",
              isValidEmailAddress: "Please enter a valid email address.",
              remote: 'Email already have been taken.'
          },
          "user[password]": {
              required: "Please enter password."
          },
          "user[confirm_password]": {
              required: "Please confirm your password.",
              equalTo: "Password does not match."
          }
        },
        errorElement : 'div',
        errorPlacement: function(error, element) {
          var placement = $(element).data('error');
          if (placement) {
            $(placement).append(error)
          } else {
            error.insertAfter(element);
          }
        }
  });
</script>

app/views/layouts/frontend/_registeration_form.html.erb
<div class="modal fade " id="register" tabindex="-1" aria-labelledby="productModal" aria-hidden="true">
   <div class="modal-dialog custom-modal modal-lg" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h2 class="modal-title title-sm mb-0 modal-title" id="exampleModalLabel">Signup</h2>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <div class="calendar-outer">
               <%= form_for(resource, as: resource_name, url: user_registration_path, :html => {:id => "register_form"}) do |f| %>
                  <div class="row">
                     <div class=" col-12">
                        <div class="form-group">
                           <label for="cc-number-label" class="control-label">Name*</label>
                           <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder:'Name', class:'input-lg form-control' %>
                        </div>
                     </div>
                     <div class=" col-12">
                        <div class="form-group">
                           <label for="cc-number-label" class="control-label">Email*</label>
                           <!-- <input id="cc-number" type="tel" value="4242424242424242"  class="input-lg form-control cc-number" autocomplete="cc-number" placeholder="•••• •••• •••• ••••" name="card_number"> -->
                           <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder:'Email', class:'input-lg form-control' %>
                        </div>
                     </div>
                     <div class="col-12">
                        <div class="form-group">
                           <label for="cc-exp-label" class="control-label">Password*</label>
                            <%= f.password_field :password, autocomplete: "current-password", class:"input-lg form-control ",   placeholder:'Password' %>
                           <!-- <input id="cc-exp" type="tel" value="12 / 2024" class="input-lg form-control cc-exp" autocomplete="cc-exp" placeholder="•• / ••••" name="card_expiry_date"> -->
                        </div>
                     </div>
                     <div class="col-12">
                        <div class="form-group">
                           <label for="cc-exp-label" class="control-label">Password*</label>
                            <%= f.password_field :password_confirmation, autocomplete: "current-password", class:"input-lg form-control ",   placeholder:'Password' %>
                           <!-- <input id="cc-exp" type="tel" value="12 / 2024" class="input-lg form-control cc-exp" autocomplete="cc-exp" placeholder="•• / ••••" name="card_expiry_date"> -->
                        </div>
                    </div>
                     <div class="col-12">
                        <div class="form-group">
                           <span class="remember pull-left"><input class="p-0 pull-left" type="checkbox">Remember Me</span>
                        </div>
                    </div>
                  </div>
                  <button type="submit" class="btn cl-btn grd-bg text-uppercase mr-md-4 mr-sm-3 mr-2" title="Register">Register</button>
               <%end%>
            </div>
         </div>
      </div>
   </div>
</div>                
<script type="text/javascript">
      $("#register_form").validate({
        rules: {
          "user[name]": {
            required: true,
            minlength: 4,
            maxlength: 50,
          },
          "user[email]": {
            required: true,
            isValidEmailAddress:true
          },
          "user[password]": {
            required: true,
            minlength: 6,
            maxlength: 20,
          },
          "user[confirm_password]": {
            required: true,
            minlength: 6,
            equalTo: "#user_password",
          }
        },
        messages: {
          "user[user_name]": {
              required: "Please enter username."
          },
          "user[email]": {
              required: "Please enter email.",
              isValidEmailAddress: "Please enter a valid email address.",
              remote: 'Email already have been taken.'
          },
          "user[password]": {
              required: "Please enter password."
          },
          "user[confirm_password]": {
              required: "Please confirm your password.",
              equalTo: "Password does not match."
          }
        },
        errorElement : 'div',
        errorPlacement: function(error, element) {
          var placement = $(element).data('error');
          if (placement) {
            $(placement).append(error)
          } else {
            error.insertAfter(element);
          }
        }
  });
</script>

app/views/layouts/shared/_message.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>