config/routes.rb
Rails.application.routes.draw do


  mount ActionCable.server => '/cable'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {
    sessions: 'sessions',
    passwords: 'passwords',
    confirmations: 'confirmations',
    :registrations => 'registrations'
  }
  get "home/index" 
  root to: 'home#index'
  
  get "home/find_jobs" => "home#find_jobs"

  resources :messages


  namespace :recruiters do
    resources :dashboard do
      collection do
          get  :my_account
          post  :my_account
          get  :user_list
          get  :chat_with_candidate
      end
    end 
    resources :jobs  do
      collection do
          get  :candidates
          get  :download_pdf
          get  :view_application
      end
      member do
        get  :approve_resume
        get  :reject_resume
      end
    end
  end


  namespace :applicants do
    resources :dashboard do
      member do
        get :application_detail
        # get :subscription
        match  :subscription, via: [:get,  :post]
      end
      collection do
        match  :job, via: [:get,  :post]
        get :my_applications
      end
    end 

    resources :jobs, only: [:show, :index] do
      member do
        post  :apply_job
        get  :add_to_favorites
        get :job_detail
        put :favorite
      end
      collection do
        get :all_jobs
        get  :my_favourite_jobs
      end
    end 
    
    # resources :recipes do
    # end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
 
	belongs_to :user, optional: true
  	has_many :applied_jobs, :class_name => 'AppliedJob', :foreign_key => :job_id
  	has_many :favorite_jobs
  	has_many :favorited_by, through: :favorite_jobs, source: :user 
  	enum job_type: [ :part_time, :full_time]
	scope :part_time, -> { where(job_type: 'part_time') }
	scope :full_time, -> { where(job_type: 'full_time') }
	scope :featured_jobs, -> {where("created_at >= ? AND created_at <= ?", Date.today -  2.months, Date.today )}

end

app/controllers/applicants/jobs_controller.rb
class Applicants::JobsController < ApplicationController
	load_and_authorize_resource
	include Applicants


	def index
		@featured_jobs = Job.featured_jobs.sort
	end

	def show
		@job =  Job.find_by_id(params[:id])
	end

	def favorite
    type = params[:type]
  	job = Job.find_by_id(params[:id])
    if type == "favorite"
      current_user.favorites << job
      redirect_to applicants_dashboard_index_path, notice: "You favorited #{job.company_name}"
    elsif type == "unfavorite"
      current_user.favorites.delete(job)
      redirect_to applicants_dashboard_index_path, notice: "Unfavorited #{job.company_name}"
    else
      redirect_to :back, notice: 'Nothing happened.'
    end
	end


	def my_favourite_jobs
		@jobs = current_user.favorites.paginate(page: params[:page], per_page: 5)
	end

	def apply_job
		job  = AppliedJob.new(job_params)
		job.status = 'active'
		job.applied_date   = Date.today
		job.save!
		EmailWorker.perform_async  'applied_job', job.id
		redirect_to applicants_dashboard_index_path
	end

	def job_detail
		@job = Job.find_by_id(params[:id])
	end







end

private

def job_params
	params.require(:applied_job).permit(:job_id, :applicant_id,  :recruiter_id, :resume,:applicant_name, :applicant_email)
end

app/controllers/concerns/recruiter.rb
module Recruiters
  include ActiveSupport::Concern

    included do
      before_action :my_uploaded_jobs, only: [:index]
    end

  def my_uploaded_jobs
    @jobs = current_user.jobs

  end

end

app/controllers/recruiters/dashboard_controller.rb
class Recruiters::DashboardController < ApplicationController

	def new
		
	end

	def index
		
	end

	def my_account
		current_user.update(user_params) if request.post?
	end
	
	def user_list
        @users = User.all 
    end 

    def chat_with_candidate
        @sender = User.find(params[:user_id])
        @receiver = User.find(params[:receiver_id])
        @messages = Message.where(sender_id: @sender.id, receiver_id: @receiver.id).or(Message.where(sender_id: @receiver.id, receiver_id: @sender.id))
        @chat_id = [@sender.id, @receiver.id].sort.join("") #generates a unique identifier for a pair of user 
    end 
end

private
def user_params
	params.require(:user).permit(:name,:dp, :qualification, :address,  :phone, :total_experience )
	
end

app/controllers/recruiters/jobs_controller.rb
class Recruiters::JobsController < ApplicationController
	load_and_authorize_resource
	include  Recruiters
	def new
		@job = Job.new
	end

	def index
		@jobs = @jobs.paginate(page: params[:page], per_page: 5)
	end

	def candidates
		@jobs =  AppliedJob.includes(:job).where(recruiter_id: current_user.id).paginate(page: params[:page], per_page: 5)
	end

	def edit
		@job = Job.find_by_id(params[:id])
	end
	
	def create
		job = Job.new(job_params)
		job.save!
		EmailWorker.perform_async  'posted_job', job.id
		redirect_to recruiters_jobs_path, notice: "Job added."
	end

	def update
		job = Job.find_by_id(params[:id])
		job.update(job_params)
		EmailWorker.perform_async  'posted_job', job.id
		redirect_to recruiters_jobs_path, notice: "Job updated."
		
	end

	def approve_resume
		byebug
		job = AppliedJob.find_by_id(params[:id])
		job.update(status: 'approved')
	end


	def reject_resume
		byebug
		job = AppliedJob.find_by_id(params[:id])
		job.update(status: 'rejected')
	end

	def destroy
		job = Job.find_by_id(params[:id])
		job.destroy
		redirect_to recruiters_jobs_path, notice: "Job deleted."
		
	end

end

private

def job_params
	params.require(:job).permit(:company_name, :title, :skills, :job_type, :description, :locality, :user_id, :category, :type, :closing_date)
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/views/recruiters/jobs/_full_time.html.erb
<div class="row">
  <%@full_time_jobs.each_with_index do |job, index| %>
    <div class="col-md-6">
        <div class="single-job-post">
             <div class="img-icon">
                <img src="images/candidates/1.jpg" alt="">
            </div>
            <div class="address">
                <h6><%= job.applicant.name.titleize %></h6>
                <p><span><%= job.job&.title&.titleize %></span></p>
                <p>Location : <%= job.job&.locality&.titleize %></p>
            </div>
            <div class="button-box">
              <%if job.resume.exists?%>
                <%= link_to "View Resume",    job.resume.url(:original, false), class:"button button-black" %>
              <%else%>
              <a href="#"class="button button-black">No resume</a>
               
               <%end%>
              <!-- <a href="<%#=job.resume.url(:original, false)%>" download="data" class="button button-black">VIEW RESUME</a> -->
            </div>
            <div class="button-box">
               <%= form_for :user, :url => chat_with_candidate_recruiters_dashboard_index_path,  :html => { :method => 'GET' } do |f| %>
                <%= hidden_field_tag "user_id", current_user.id%>
                <%= hidden_field_tag "receiver_id", job.applicant.id%>
                <%= f.submit "Chat"%>
            <% end %>
            </div>

        </div>  

    </div>
    <%end%>
    <div class="col-md-12">
        <div class="loadmorebtn">
            <a href="#" class="button">Load More</a>
        </div>
    </div>  
</div>

app/views/recruiters/jobs/_job_list.html.erb
<div class="table-responsive"  style="width: 90%">
  <table class="table table-bordered table-hover logstableBox" id="table-1">
    <%if @jobs.present?%>   
    <thead  class="thead-light">

      <tr>
            <th scope="col">Company Name</th>
            <th scope="col">Job Title</th>
            <th scope="col">Job Type</th>
            <th scope="col">Job Categroy</th>
            <th colspan="3">Action</th>
          </tr>
    </thead>
        <tbody>

          <%@jobs.each_with_index do |job, index| %>
          <tr>
            <td><%= job.company_name%></td>
            <td><%= job.title%></td>
            <td><%= job.job_type&.titleize%></td>
            <td><%= job.category%></td>
            <td>
              <!-- <a  class="btn btn-primary" href="<%= recruiters_job_path(job.id) %>"><i class="far fa-eye"></i></a>
              <a  class="btn btn-success" href="<%= edit_recruiters_dashboard_path(job.id) %>"><i class="fas fa-edit"></i></a>
            <a  class="btn btn-danger" href="<%= recruiters_job_path(job.id) %>"  method="delete"><i class="far fa-trash-alt"></i></a> -->
             <%= link_to 'Edit', edit_recruiters_job_path(id: job.id) %>
             <%#= link_to 'View', edit_recruiters_job_path(id: job.id) %>
             <%= link_to 'Delete', recruiters_job_path(id: job.id) ,:method => :delete %>
            </td>
          </tr>
          <%end%>
          
        </tbody>

    </table>
    <%end%>
</div>

app/views/recruiters/jobs/_part_time.html.erb
<div class="row">
  <%@part_time_jobs.each_with_index do |job, index| %>
    <div class="col-md-6">
        <div class="single-job-post">
             <div class="img-icon">
                <img src="images/candidates/1.jpg" alt="">
            </div>
            <div class="address">
                <h6><%= job.applicant.name.titleize %></h6>
                <p><span><%= job.job&.title&.titleize %></span></p>
                <p>Location : <%= job.job&.locality&.titleize %></p>
            </div>
            <div class="button-box">
              <%if job.resume.exists?%>
                <%= link_to "View Resume",    job.resume.url(:original, false), class:"button button-black" %>
              <%else%>
              <a href="#"class="button button-black">No resume</a>
               
               <%end%>
              <!-- <a href="<%#=job.resume.url(:original, false)%>" download="data" class="button button-black">VIEW RESUME</a> -->
            </div>
            <div class="button-box">
               <%= form_for :user, :url => chat_with_candidate_recruiters_dashboard_index_path,  :html => { :method => 'GET' } do |f| %>
                <%= hidden_field_tag "user_id", current_user.id%>
                <%= hidden_field_tag "receiver_id", job.applicant.id%>
                <%= f.submit "Chat"%>
            <% end %>
            </div>

        </div>  

    </div>
    <%end%>
    <div class="col-md-12">
        <div class="loadmorebtn">
            <a href="#" class="button">Load More</a>
        </div>
    </div>  
</div>

app/views/recruiters/jobs/candidates.html.erb
<section class="featured-job-area feature-padding">
            <div class="container">
                <!-- Section Tittle -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-tittle text-center">
                            <span>Recent Applications</span>
                            <h2>Featured Applicants</h2>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-xl-10">
                        <!-- single-job-content -->
                        <%@jobs.each_with_index do |job, index| %>
                        <div class="single-job-items mb-30">
                            <div class="job-items">
                                <div class="company-img">
                                    <%=link_to( image_pack_tag('media/img/company.png', :class => 'company_img', alt: "company-image"),  root_path) %>
                                </div>
                                <div class="job-tittle">
                                    <a href="job_details.html"><h4><%= job.applicant.name.titleize %></h4></a>
                                    <ul>
                                        <li><%= job.job&.title&.titleize %></li>
                                        <li><%= job.job&.job_type&.titleize %></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="items-link f-right">
                              <%if job.resume.exists?%>
                                <!-- <a href="job_details.html"><%= job.job&.job_type&.titleize %></a> -->
                                <%= link_to "View Resume",    job.resume.url(:original, false) %>
                                <%= link_to "View Application", view_application_recruiters_jobs_url %>
                              <%else%>
                                <a href="#"class="button button-black">No resume</a>  
                               <%end%>
                            </div>
                        </div>
                        <%end%>
                    </div>
                </div>
            </div>
        </section>

app/views/recruiters/jobs/edit.html.erb
<section class="contact-section">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h2 class="contact-title">Edit job</h2>
      </div>
      <div class="col-lg-8">
        <%= form_for @job, url: recruiters_job_path,  method: :patch, class:"form-contact contact_form", id: "contactForm", novalidate: "novalidate" do |f| %>
        <div class="row">
          <div class="col-12">
            <div class="form-group">
              <%= f.text_field :company_name ,  placeholder: "Enter company name", class: "form-control valid" %>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <%= f.text_field :title ,  placeholder: "Enter job title", class: "form-control valid"%>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <%= f.select :job_type, options_for_select(Job.job_types.map {|key, value| [key.titleize, Job.job_types.key(value)]},selected: @job.job_type), { include_blank: 'Select Job Type' }%>
            </div>
          </div>
          <div class="col-12">
            <div class="form-group">
              <%= f.text_field :category ,  placeholder: "Enter job category", class: "form-control valid"%>
            </div>
          </div>
          <div class="col-12">
            <div class="form-group">
              <%= f.text_field :closing_date ,  placeholder: "yyyy-mm-dd"%>
              <%= f.text_field :closing_date ,  placeholder: "yyyy-mm-dd" , class: "form-control valid"%>
            </div>
          </div>
        </div>
        <div class="form-group mt-3">
          <button type="submit" class="button button-contactForm boxed-btn">Send</button>
        </div>
        <%end%>
      </div>
    </div>
  </div>
</section>

app/views/recruiters/jobs/index.html.erb
<style type="text/css">
   h4 {
   margin: 2rem 0rem 1rem;
}
 .table-image td, .table-image th {
   vertical-align: middle;
}
.table-responsive{
    margin-top: 20%;
    padding-left: 5%;
    margin-right: -10%
}
 
</style>
<div class="job-categroy-area2 pt-130 pb-100 pt-sm-60 pb-sm-40">
  <div class="container">
    <div id="jobs">
    <%= render "job_list" %>
    <%= will_paginate @jobs%>
    </div>
  </div>
</div>
<div class="pagination-outer">
  <nav aria-label="Page navigation">
  </nav>
</div>
  

app/views/recruiters/jobs/index.js.erb
 $("#jobs").html('<%=  escape_javascript(render :partial => 'job_list') %>');
$('.pagination a').attr('data-remote', 'true');

app/views/recruiters/jobs/new.html.erb
<section class="contact-section">
  <div class="container">
      <div class="row">
          <div class="col-12">
              <h2 class="contact-title">Post a job</h2>
          </div>
          <div class="col-lg-8">
              <!-- <form class="form-contact contact_form" action="contact_process.php" method="post" id="contactForm" novalidate="novalidate"> -->
              <%= form_for @job, url: recruiters_jobs_path,  method: :post, class:"form-contact contact_form", id: "contactForm", novalidate: "novalidate" do |f| %>
                  <div class="row">
                      <div class="col-12">
                          <div class="form-group">
                              <!-- <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'" placeholder=" Enter Message"></textarea> -->
                              <%= f.text_field :company_name ,  placeholder: "Enter company name", class: "form-control valid" %>
                          </div>
                      </div>
                      <div class="col-sm-6">
                          <div class="form-group">
                              <!-- <input class="form-control valid" name="name" id="name" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'" placeholder="Enter your name"> -->
                              <%= f.text_field :title ,  placeholder: "Enter job title", class: "form-control valid"%>
                          </div>
                      </div>
                      <div class="col-sm-6">
                          <div class="form-group">
                              <!-- <input class="form-control valid" name="email" id="email" type="email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" placeholder="Email"> -->
                              <%= f.select :job_type, options_for_select(Job.job_types.map {|key, value| [key.titleize, Job.job_types.key(value)]}), { include_blank: 'Select Job Type' }%>
                          </div>
                      </div>
                      <div class="col-12">
                          <div class="form-group">
                              <!-- <input class="form-control" name="subject" id="subject" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Subject'" placeholder="Enter Subject"> -->
                              <%= f.text_field :category ,  placeholder: "Enter job category", class: "form-control valid"%>
                          </div>
                      </div>
                      <div class="col-12">
                          <div class="form-group">
                              <!-- <input class="form-control" name="subject" id="subject" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Subject'" placeholder="Enter Subject"> -->
                              <%= f.text_field :closing_date ,  placeholder: "yyyy-mm-dd" , class: "form-control valid"%>
                          </div>
                      </div>
                  </div>
                  <div class="form-group mt-3">
                      <button type="submit" class="button button-contactForm boxed-btn">Send</button>
                  </div>
              <%end%>
          </div>
      </div>
  </div>
</section>

app/views/recruiters/jobs/view_application.html.erb
<main>

        <!-- Hero Area Start-->
        <div class="slider-area ">
        <div class="single-slider section-overly slider-height2 d-flex align-items-center" data-background="assets/img/hero/about.jpg">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center">
                            <h2>UI/UX Designer</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
        <!-- Hero Area End -->
        <!-- job post company Start -->
        <div class="job-post-company pt-120 pb-120">
            <div class="container">
                <div class="row justify-content-between">
                    <!-- Left Content -->
                    <div class="col-xl-7 col-lg-8">
                        <!-- job single -->
                        <div class="single-job-items mb-50">
                            <div class="job-items">
                                <div class="company-img company-img-details">
                                    <a href="#"><img src="assets/img/icon/job-list1.png" alt=""></a>
                                </div>
                                <div class="job-tittle">
                                    <a href="#">
                                        <h4>Digital Marketer</h4>
                                    </a>
                                    <ul>
                                        <li>Creative Agency</li>
                                        <li><i class="fas fa-map-marker-alt"></i>Athens, Greece</li>
                                        <li>$3500 - $4000</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                          <!-- job single End -->
                       
                        <div class="job-post-details">
                            <div class="post-details1 mb-50">
                                <!-- Small Section Tittle -->
                                <div class="small-section-tittle">
                                    <h4>Job Description</h4>
                                </div>
                                <p>It is a long established fact that a reader will beff distracted by vbthe creadable content of a page when looking at its layout. The pointf of using Lorem Ipsum is that it has ahf mcore or-lgess normal distribution of letters, as opposed to using, Content here content here making it look like readable.</p>
                            </div>
                            <div class="post-details2  mb-50">
                                 <!-- Small Section Tittle -->
                                <div class="small-section-tittle">
                                    <h4>Required Knowledge, Skills, and Abilities</h4>
                                </div>
                               <ul>
                                   <li>System Software Development</li>
                                   <li>Mobile Applicationin iOS/Android/Tizen or other platform</li>
                                   <li>Research and code , libraries, APIs and frameworks</li>
                                   <li>Strong knowledge on software development life cycle</li>
                                   <li>Strong problem solving and debugging skills</li>
                               </ul>
                            </div>
                            <div class="post-details2  mb-50">
                                 <!-- Small Section Tittle -->
                                <div class="small-section-tittle">
                                    <h4>Education + Experience</h4>
                                </div>
                               <ul>
                                   <li>3 or more years of professional design experience</li>
                                   <li>Direct response email experience</li>
                                   <li>Ecommerce website design experience</li>
                                   <li>Familiarity with mobile and web apps preferred</li>
                                   <li>Experience using Invision a plus</li>
                               </ul>
                            </div>
                        </div>

                    </div>
                    <!-- Right Content -->
                    <div class="col-xl-4 col-lg-4">
                        <div class="post-details3  mb-50">
                            <!-- Small Section Tittle -->
                           <div class="small-section-tittle">
                               <h4>Job Overview</h4>
                           </div>
                          <ul>
                              <li>Posted date : <span>12 Aug 2019</span></li>
                              <li>Location : <span>New York</span></li>
                              <li>Vacancy : <span>02</span></li>
                              <li>Job nature : <span>Full time</span></li>
                              <li>Salary :  <span>$7,800 yearly</span></li>
                              <li>Application date : <span>12 Sep 2020</span></li>
                          </ul>
                         <div class="apply-btn2">
                            <a href="#" class="btn">Apply Now</a>
                         </div>
                       </div>
                        <div class="post-details4  mb-50">
                            <!-- Small Section Tittle -->
                           <div class="small-section-tittle">
                               <h4>Company Information</h4>
                           </div>
                              <span>Colorlib</span>
                              <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                            <ul>
                                <li>Name: <span>Colorlib </span></li>
                                <li>Web : <span> colorlib.com</span></li>
                                <li>Email: <span>carrier.colorlib@gmail.com</span></li>
                            </ul>
                       </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- job post company End -->

    </main>