config/routes.rb
Rails.application.routes.draw do


  mount ActionCable.server => '/cable'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {
    sessions: 'sessions',
    passwords: 'passwords',
    confirmations: 'confirmations',
    :registrations => 'registrations'
  }
  get "home/index" 
  root to: 'home#index'
  
  get "home/find_jobs" => "home#find_jobs"

  resources :messages


  namespace :recruiters do
    resources :dashboard do
      collection do
          get  :my_account
          post  :my_account
          get  :user_list
          get  :chat_with_candidate
      end
    end 
    resources :jobs  do
      collection do
          get  :candidates
          get  :download_pdf
          get  :view_application
      end
      member do
        get  :approve_resume
        get  :reject_resume
      end
    end
  end


  namespace :applicants do
    resources :dashboard do
      member do
        get :application_detail
        # get :subscription
        match  :subscription, via: [:get,  :post]
      end
      collection do
        match  :job, via: [:get,  :post]
        get :my_applications
      end
    end 

    resources :jobs, only: [:show, :index] do
      member do
        post  :apply_job
        get  :add_to_favorites
        get :job_detail
        put :favorite
      end
      collection do
        get :all_jobs
        get  :my_favourite_jobs
      end
    end 
    
    # resources :recipes do
    # end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/applicants/dashboard_controller.rb
class Applicants::DashboardController < ApplicationController
	
	include Applicants

	def new
		
	end

	def index
		get_all_jobs
		@part_time_jobs = @jobs.part_time   
		@full_time_jobs =@jobs.full_time
	end

	def my_account
				current_user.update(user_params) if request.post?
	end

	def my_applications
		@my_jobs = current_user.applied_jobs
	end


	def application_detail
		@applied_job = AppliedJob.find_by_job_id(params[:id])
	end

	def subscription
		if request.post?
		check_stripe_customer_id  unless current_user.stripe_customer_id  			
		Stripe.api_key = STRIPE_SECRET
		# Create a  payment
		begin
			payment = Stripe::PaymentMethod.create({
								  type: 'card',
									card: {
									number: params[:card_number],
									exp_month: params[:exp_month],
									exp_year: params[:exp_year],
									cvc: params[:cvc]
									}
								})

			puts "============payment created=========================="

		Stripe::PaymentMethod.attach(
									  payment.id,
									  {customer: current_user.stripe_customer_id},
									)
		puts "============pay method attached=========================="
		# update customer default payment method
			pay_method  = Stripe::Customer.update(
												current_user.stripe_customer_id, 
												{invoice_settings: 
													{default_payment_method: payment.id}
												},
											)
		puts "============ pay method updated=========================="
		# Create subscription
			plan = Plan.first
			subscribe  =	Stripe::Subscription.create({
											  customer: current_user.stripe_customer_id,
											  items: [
											    {price: plan.stripe_price_id},
											  ]
											})
			puts "============subscription created=========================="
			subscription = current_user.build_subscription(subscription_params) if subscribe
		rescue StandardError => e
			puts "============#{e.message}=========================="
		end
			
		# if request.post?
			# success = false
			# Stripe.api_key = STRIPE_SECRET
			# 	begin
			# 		card = Stripe::Token.create({
			# 			card: {
			# 			number: params[:card_number],
			# 			exp_month: params[:exp_month],
			# 			exp_year: params[:exp_year],
			# 			cvc: params[:cvc]
			# 			},
			# 		})

			# 	  charge = Stripe::Charge.create({
			# 		  amount: params[:paid_amount].to_i*100,  
			# 		  currency: "INR",
			# 		  source: card.id,
			# 		})

			# 		subscription = current_user.build_subscription(subscription_params) if charge&.paid
			# 		subscription.save!
					# render json: {success: true, message:'Subscription done.'}

				# rescue StandardError => e
				#   flash[:error] = e.message
				# end
				

		end

	end
	
end
private
	def subscription_params
		params.permit(:user_id, :paid_amount,:start_date,:end_date)
	end

app/controllers/applicants/jobs_controller.rb
class Applicants::JobsController < ApplicationController
	load_and_authorize_resource
	include Applicants


	def index
		@featured_jobs = Job.featured_jobs.sort
	end

	def show
		@job =  Job.find_by_id(params[:id])
	end

	def favorite
    type = params[:type]
  	job = Job.find_by_id(params[:id])
    if type == "favorite"
      current_user.favorites << job
      redirect_to applicants_dashboard_index_path, notice: "You favorited #{job.company_name}"
    elsif type == "unfavorite"
      current_user.favorites.delete(job)
      redirect_to applicants_dashboard_index_path, notice: "Unfavorited #{job.company_name}"
    else
      redirect_to :back, notice: 'Nothing happened.'
    end
	end


	def my_favourite_jobs
		@jobs = current_user.favorites.paginate(page: params[:page], per_page: 5)
	end

	def apply_job
		job  = AppliedJob.new(job_params)
		job.status = 'active'
		job.applied_date   = Date.today
		job.save!
		EmailWorker.perform_async  'applied_job', job.id
		redirect_to applicants_dashboard_index_path
	end

	def job_detail
		@job = Job.find_by_id(params[:id])
	end







end

private

def job_params
	params.require(:applied_job).permit(:job_id, :applicant_id,  :recruiter_id, :resume,:applicant_name, :applicant_email)
end

app/controllers/concerns/applicants.rb
module Applicants
  include ActiveSupport::Concern

    # included do
    #   before_action :check_stripe_customer_id, only: [:subscription]
    # end

  def get_all_jobs
    @jobs = Job.all.paginate(page: params[:page], per_page: 25)

  end

  def check_stripe_customer_id
    Stripe.api_key = STRIPE_SECRET
    cutomer = Stripe::Customer.create({
          email: current_user.email,
        })  
    user.update(stripe_customer_id: cutomer.id)
  end

end

app/controllers/recruiters/dashboard_controller.rb
class Recruiters::DashboardController < ApplicationController

	def new
		
	end

	def index
		
	end

	def my_account
		current_user.update(user_params) if request.post?
	end
	
	def user_list
        @users = User.all 
    end 

    def chat_with_candidate
        @sender = User.find(params[:user_id])
        @receiver = User.find(params[:receiver_id])
        @messages = Message.where(sender_id: @sender.id, receiver_id: @receiver.id).or(Message.where(sender_id: @receiver.id, receiver_id: @sender.id))
        @chat_id = [@sender.id, @receiver.id].sort.join("") #generates a unique identifier for a pair of user 
    end 
end

private
def user_params
	params.require(:user).permit(:name,:dp, :qualification, :address,  :phone, :total_experience )
	
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
	def recruiter_id(job_id)
		Job.find_by_id(job_id).user_id

	end

	def already_applied(job)
		job.applied_jobs.find_by(applicant_id:current_user.id)
	end

	def is_favorite(job)
		job.favorited_by.map(&:id).include? current_user.id
	end

	def applied_date(job)
		if job.applied_date.present?
			job.applied_date.try(:strftime, "%D")
		else
			''
		end
	end
 def current_class?(path)
    current_route = Rails.application.routes.recognize_path(path)
    return 'active' if current_page?(path) or params[:controller] == current_route[:controller]

    # return 'active' if request.path == path
    ''
  end
end

app/views/applicants/dashboard/_full_time.html.erb
<div class="row">
	<%@full_time_jobs.each_with_index do |job, index| %>
    <div class="col-md-6">
        <div class="single-job-post">
             <div class="img-icon">
                <%#= image_tag 'company-logo/1.png', alt: 'icon' %>
            </div>
            <div class="address">
                <h6><%= job.company_name.titleize %></h6>
                <p><span><%= job.title.titleize %></span></p>
                <p>Location : <%= job.locality.titleize %></p>
                <p>Job Type : <%= job.job_type.titleize %></p>
            </div>
            <div class="button-box"><a href="<%= applicants_job_path(job.id)%>" class="button button-black">APPLY NOW</a></div>
               <div class="button-box">
	           <%= form_for :user, :url => chat_with_candidate_recruiters_dashboard_index_path,  :html => { :method => 'GET' } do |f| %>
	            <%= hidden_field_tag "user_id", current_user.id%>
	            <%#= hidden_field_tag "receiver_id", job.recruiter.id%>
	            <%= f.submit "Chat"%>
	        <% end %>
	        </div>
            
        </div>                                    
    </div>
    <%end%>
</div>

app/views/applicants/dashboard/_part_time.html.erb
<div class="row">
	<%@part_time_jobs.each_with_index do |job, index| %>
    <div class="col-md-6">
        <div class="single-job-post">
             <div class="img-icon">
                <%#= image_tag 'company-logo/1.png', alt: 'icon' %>
            </div>
            <div class="address">
                <h6><%= job.company_name.titleize %></h6>
                <p><span><%= job.title.titleize %></span></p>
                <p>Location : <%= job.locality.titleize %></p>
                <p>Job Type : <%= job.job_type.titleize %></p>
            </div>
            <div class="button-box"><a href="<%= applicants_job_path(job.id)%>" class="button button-black">APPLY NOW</a></div>
	          <div class="button-box">
	           <%= form_for :user, :url => chat_with_candidate_recruiters_dashboard_index_path,  :html => { :method => 'GET' } do |f| %>
	            <%= hidden_field_tag "user_id", current_user.id%>
	            <%= hidden_field_tag "receiver_id", 2%>
	            <%= f.submit "Chat"%>
	        <% end %>
	        </div>
        </div>                                    
    </div>
    <%end%>
</div>

app/views/applicants/dashboard/_payment_modal.html.erb
<div class="modal fade " id="bookLesson" tabindex="-1" aria-labelledby="bookLessonLabel" aria-hidden="true">
   <div class="modal-dialog custom-modal modal-lg" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h2 class="modal-title title-sm mb-0 modal-title" id="exampleModalLabel">Payment</h2>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <div class="calendar-outer">
               <%= form_tag subscription_applicants_dashboard_url(current_user.id), :method => 'post', :class=>'form-contact contact_form', id:"payment-form", novalidate:'novalidate' do %>
                  <%= hidden_field_tag :paid_amount, 10 %>
                  <%= hidden_field_tag :user_id, current_user.id %>
                  <%= hidden_field_tag :start_date, Date.today %>
                  <%= hidden_field_tag :end_date, Date.today + 1.year %>
                  <div class="row">
                     <div class="col-md-6 col-12">
                        <div class="form-group">
                           <label for="cc-number-label" class="control-label">Card number formatting <small class="text-muted">[<span class="cc-brand"></span>]</small></label>
                           <input id="cc-number" type="tel" value="4242424242424242"  class="input-lg form-control cc-number" autocomplete="cc-number" placeholder="•••• •••• •••• ••••" name="card_number">
                        </div>
                     </div>
                     <div class="col-md-6 col-12">
                        <div class="form-group">
                           <label for="cc-exp-label" class="control-label">Card expiry formatting</label>
                           <input id="cc-exp" type="tel" value="12 / 2024" class="input-lg form-control cc-exp" autocomplete="cc-exp" placeholder="•• / ••••" name="card_expiry_date">
                        </div>
                     </div>
                     <div class="col-md-6 col-12">
                        <div class="form-group">
                           <label for="cc-cvc-label" class="control-label">Card CVC formatting</label>
                           <input id="cc-cvc" type="password" value="123" class="input-lg form-control cc-cvc" autocomplete="off" placeholder="•••" name="card_cvc">
                        </div>
                     </div>
                  </div>
                  <button type="submit" class="make_stripe_payment btn cl-btn grd-bg text-uppercase search_result mr-md-4 mr-sm-3 mr-2" title="Make Payment">Make Payment</button>
                  <a href="javascript:void(0);"  class="btn cl-btn white-btn text-uppercase" data-dismiss="modal" title="Close">Close</a>
               <%end%>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/applicants/dashboard/application_detail.html.erb
<main>

        <!-- Hero Area Start-->
        <div class="slider-area ">
        <div class="single-slider section-overly slider-height2 d-flex align-items-center" data-background="assets/img/hero/about.jpg">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center">
                            <h2><%=@applied_job.job.title&.titleize%></h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
        <!-- Hero Area End -->
        <!-- job post company Start -->
        <div class="job-post-company pt-120 pb-120">
            <div class="container">
                <div class="row justify-content-between">
                    <!-- Left Content -->
                    <div class="col-xl-7 col-lg-8">
                        <!-- job single -->
                        <div class="single-job-items mb-50">
                            <div class="job-items">
                                <div class="company-img company-img-details">
                                    <a href="#"><img src="assets/img/icon/job-list1.png" alt=""></a>
                                </div>
                                <div class="job-tittle">
                                    <a href="#">
                                        <h4><%=@applied_job.job.company_name&.titleize%></h4>
                                    </a>
                                    <ul>
                                        <li><%=@applied_job.job.title&.titleize%></li>
                                        <li><i class="fas fa-map-marker-alt"></i><%=@applied_job.job.locality&.titleize%></li>
                                        <li><%=@applied_job.job.job_type&.titleize%></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                          <!-- job single End -->
                       
                        <div class="job-post-details">
                            <div class="post-details1 mb-50">
                                <!-- Small Section Tittle -->
                                <div class="small-section-tittle">
                                    <h4>Job Description</h4>
                                </div>
                                <p><%#=  @applied_job.job.description %>.</p>
                            </div>
                            <div class="post-details2  mb-50">
                                 <!-- Small Section Tittle -->
                                <div class="small-section-tittle">
                                    <h4>Required Knowledge, Skills, and Abilities</h4>
                                </div>
                               <ul>
                                   <li>System Software Development</li>
                                   <li>Mobile Applicationin iOS/Android/Tizen or other platform</li>
                                   <li>Research and code , libraries, APIs and frameworks</li>
                                   <li>Strong knowledge on software development life cycle</li>
                                   <li>Strong problem solving and debugging skills</li>
                               </ul>
                            </div>
                            <div class="post-details2  mb-50">
                                 <!-- Small Section Tittle -->
                                <div class="small-section-tittle">
                                    <h4>Education + Experience</h4>
                                </div>
                               <ul>
                                   <li>3 or more years of professional design experience</li>
                                   <li>Direct response email experience</li>
                                   <li>Ecommerce website design experience</li>
                                   <li>Familiarity with mobile and web apps preferred</li>
                                   <li>Experience using Invision a plus</li>
                               </ul>
                            </div>
                        </div>

                    </div>
                    <!-- Right Content -->
                    <div class="col-xl-4 col-lg-4">
                        <div class="post-details3  mb-50">
                            <!-- Small Section Tittle -->
                           <div class="small-section-tittle">
                               <h4>Job Overview</h4>
                           </div>
                          <ul>
                              <li>Posted date : <span><%=@applied_job.job.created_at.try(:strftime, "%d-%m-%y")%></span></li>
                              <li>Location : <span><%=@applied_job.job.locality&.titleize%></span></li>
                              <li>Vacancy : <span>02</span></li>
                              <li>Job nature : <span><%=@applied_job.job.job_type&.titleize%></span></li>
                          </ul>
                         <div class="apply-btn2">
                            <a href="<%= applicants_job_path(@applied_job.job.id)%>" class="btn">Apply Now</a>
                         </div>
                       </div>
<!--                         <div class="post-details4  mb-50">
                           <div class="small-section-tittle">
                               <h4>Company Information</h4>
                           </div>
                              <span>Colorlib</span>
                              <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                            <ul>
                                <li>Name: <span>Colorlib </span></li>
                                <li>Web : <span> colorlib.com</span></li>
                                <li>Email: <span>carrier.colorlib@gmail.com</span></li>
                            </ul>
                       </div> -->
                    </div>
                </div>
            </div>
        </div>
        <!-- job post company End -->

    </main>

app/views/applicants/dashboard/index.html.erb
<div class="job-post-area pb-100 pb-sm-35">
    <div class="container">
        <!-- Section Title Start -->
        <div class="row">
            <div class="col-md-12">
                <div class="section-title text-center ">
                    <h2>All Job</h2>
                    <p>Apply for jobs...</p>
                </div>
            </div>
        </div>
        <%= render partial: 'layouts/shared/search'%>
        <!-- Section Title End -->
        <div class="all-job-post">
            <!-- Nav tabs -->
            <div class="post-tab nav">
                <a class="nav-link active show" data-toggle="tab" href="#recent_job">RECENT JOBS</a>
            </div>                            
            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane active show" id="recent_job">
                    <div class="row">
                    	<%@jobs.each_with_index do |job, index| %>
                        <div class="col-md-6">
                            <div class="single-job-post">
                                 <div class="img-icon">
                                    <%#= image_tag 'company-logo/1.png', alt: 'icon' %>
                                     <img src='/assets/images/company-logo/company.png' alt='icon' />
                                </div>
                                <div class="address">
                                    <h6><%= job.company_name.titleize %></h6>
                                    <p><span><%= job.title&.titleize %></span></p>
                                    <p>Location : <%= job.locality&.titleize %></p>
                                    <p>Job Type : <%= job.job_type&.titleize %></p>
                                </div>
                              <%if already_applied(job).present?%>
                                Already Applied
                              <%else%>
                              <div class="button-box"><a href="<%= applicants_job_path(job.id)%>" class="button button-black">APPLY NOW</a></div> </a>
                               
                               <%end%>
                              <!-- <a href="<%#=job.resume.url(:original, false)%>" download="data" class="button button-black">VIEW RESUME</a> -->
                            <!-- </div> -->
                                
                            </div>                                    
                        </div>
                        <%end%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/applicants/dashboard/job.html.erb
<div class="our-services section-pad-t30">
            <div class="container">
                <!-- Section Tittle -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-tittle text-center">
                            <span>FEATURED TOURS Packages</span>
                            <h2>Browse Top Categories </h2>
                        </div>
                    </div>
                </div>
                <div class="row d-flex justify-contnet-center">
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-services text-center mb-30">
                            <div class="services-ion">
                                <span class="flaticon-tour"></span>
                            </div>
                            <div class="services-cap">
                               <h5><a href="job_listing.html">Design &amp; Creative</a></h5>
                                <span>(653)</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-services text-center mb-30">
                            <div class="services-ion">
                                <span class="flaticon-cms"></span>
                            </div>
                            <div class="services-cap">
                               <h5><a href="job_listing.html">Design &amp; Development</a></h5>
                                <span>(658)</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-services text-center mb-30">
                            <div class="services-ion">
                                <span class="flaticon-report"></span>
                            </div>
                            <div class="services-cap">
                               <h5><a href="job_listing.html">Sales &amp; Marketing</a></h5>
                                <span>(658)</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-services text-center mb-30">
                            <div class="services-ion">
                                <span class="flaticon-app"></span>
                            </div>
                            <div class="services-cap">
                               <h5><a href="job_listing.html">Mobile Application</a></h5>
                                <span>(658)</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-services text-center mb-30">
                            <div class="services-ion">
                                <span class="flaticon-helmet"></span>
                            </div>
                            <div class="services-cap">
                               <h5><a href="job_listing.html">Construction</a></h5>
                                <span>(658)</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-services text-center mb-30">
                            <div class="services-ion">
                                <span class="flaticon-high-tech"></span>
                            </div>
                            <div class="services-cap">
                               <h5><a href="job_listing.html">Information Technology</a></h5>
                                <span>(658)</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-services text-center mb-30">
                            <div class="services-ion">
                                <span class="flaticon-real-estate"></span>
                            </div>
                            <div class="services-cap">
                               <h5><a href="job_listing.html">Real Estate</a></h5>
                                <span>(658)</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-services text-center mb-30">
                            <div class="services-ion">
                                <span class="flaticon-content"></span>
                            </div>
                            <div class="services-cap">
                               <h5><a href="job_listing.html">Content Writer</a></h5>
                                <span>(658)</span>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- More Btn -->
                <!-- Section Button -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="browse-btn2 text-center mt-50">
                            <a href="<%=all_jobs_applicants_dashboard_index_url%>" class="border-btn2">Browse All Sectors</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<%= render partial:'featured_job'%>

app/views/applicants/dashboard/job_application.html.erb
<div class="job-post-area pb-100 pb-sm-35">
    <div class="container">
        <!-- Section Title Start -->
        <div class="row">
            <div class="col-md-12">
                <div class="section-title text-center ">
                    <h2>My applied Jobs</h2>
                </div>
            </div>
        </div>
        <!-- Section Title End -->
        <div class="all-job-post">
            <!-- Nav tabs -->
            <div class="post-tab nav">
                <a class="nav-link active show" data-toggle="tab" href="#recent_job">MY APPLICATION</a>
            </div>                            
            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane active show" id="recent_job">
                    <div class="row">
                    	<%@my_jobs.each_with_index do |job, index| %>
                        <div class="col-md-6">
                            <div class="single-job-post">
                                 <div class="img-icon">
                                    <%#= image_tag 'company-logo/1.png', alt: 'icon' %>
                                     <img src='/assets/images/company-logo/company.png' alt='icon' />
                                </div>
                                <div class="address">
                                    <h6><%= job.job.company_name.titleize %></h6>
                                    <p><span><%= job.job.title.titleize %></span></p>
                                    <p>Location : <%= job.job.locality.titleize %></p>
                                    <p>Job Type : <%= job.job.job_type.titleize %></p>
                                </div>
                                <div class="button-box"><a href="<%= applicants_job_path(job.id)%>" class="button button-black">VIEW APPLICATION</a></div> </a>
                            </div>                                    
                        </div>
                        <%end%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/applicants/dashboard/my_applications.html.erb
<section class="featured-job-area feature-padding">
            <div class="container">
                <!-- Section Tittle -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-tittle text-center">
                            <h2>Applied Jobs</h2>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-xl-10">
                        <!-- single-job-content -->
                          <%@my_jobs.each_with_index do |job, index| %>
                        <div class="single-job-items mb-30">
                            <div class="job-items">
                                <div class="company-img">
                                    <a href="job_details.html"><img src="assets/img/icon/job-list1.png" alt=""></a>
                                </div>
                                <div class="job-tittle">
                                    <a href="job_details.html"><h4><%= job.job&.company_name&.titleize %></h4></a>
                                    <ul>
                                        <li></li>
                                        <li><i class="fas fa-map-marker-alt"></i><%= job.job&.locality&.titleize%></li>
                                        <li><%= job.job&.job_type&.titleize %></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="items-link f-right">
                                <a href="<%=application_detail_applicants_dashboard_path(job.job_id)%>">View Application</a>
                            </div>
                        </div>
                          <%end%>
                    </div>
                </div>
            </div>
        </section>